# Generated by Django 4.2.7 on 2024-02-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='zipcode',
            field=models.TextField(),
        ),
    ]
